name: 🔀 Sync mirror to Gitee

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Sync:
    if: github.repository == 'ljtang2009/utools-plugins-spider-monorepo'
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:ljtang2009/utools-plugins-spider-monorepo.git
          destination-repo: git@gitee.com:tanglijin2009/utools-plugins-spider-monorepo.git

